# Generated by Django 2.2.9 on 2020-01-31 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigIntegerField(help_text='ID bank', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Branch Name', max_length=49)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(help_text='Branch Name', max_length=74, null=True)),
                ('address', models.CharField(help_text='Branch Address', max_length=195)),
                ('ifsc', models.CharField(help_text='Branch IFSC code', max_length=11)),
                ('city', models.CharField(help_text='Branch City', max_length=300)),
                ('district', models.CharField(help_text='Branch District', max_length=50)),
                ('state', models.CharField(help_text='branch state', max_length=26)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bank')),
            ],
        ),
    ]
