# Generated by Django 2.2.9 on 2020-02-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(help_text='Bank Name', max_length=49),
        ),
    ]
